### ISSUE TITLE
Guide to change opacity/brightness of   --bgo:  when blur_slider is enabled 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#2]
## Question

When the blur is not enabled I can change the ARGB color of   --bgo: inside the code  to match it with fg but when the blur is on i couldn't find a way to change it to  match  background 

>how to change the dark area color to match it with background which is lighter?
>![Screenshot_2024-06-30-09-52-29-32_4d38fce200f96aeac5e860e739312e76](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/cd3a1e30-2273-49e9-b06b-476460f08685)

**Comment by p0bo** [comment]
![Screenshot_2024-06-30-11-56-13-84_4d38fce200f96aeac5e860e739312e76](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/3d6f8853-d553-45e7-a59e-88718421db8b)
If I change the opacity here it changes the opacity globally but I only want to change the pacity for tables in search , top anime , ranking etc . Not everywhere

**Comment by KanashiiDev** [comment]
> ## Question
> When the blur is not enabled I can change the ARGB color of --bgo: inside the code to match it with fg but when the blur is on i couldn't find a way to change it to match background
> 
> > how to change the dark area color to match it with background which is lighter?
> > ![Screenshot_2024-06-30-09-52-29-32_4d38fce200f96aeac5e860e739312e76](https://private-user-images.githubusercontent.com/154865357/344443345-cd3a1e30-2273-49e9-b06b-476460f08685.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODIxNzIsIm5iZiI6MTcxOTc4MTg3MiwicGF0aCI6Ii8xNTQ4NjUzNTcvMzQ0NDQzMzQ1LWNkM2ExZTMwLTIyNzMtNDllOS1iMDZiLTQ3NjQ2MGYwODY4NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQyMTExMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjE5ODQ2YzM3NjcyN2JjODU5Y2I5N2I2NDllOGFiODk0MjZmNWJkZjMxMmFkZTc3OWViMGE1M2RkYjBlOGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HU8ply20wfSZGVDbPi1jMpqR7Qy4Ka-aZHzoacM782I)

this bug fixed in 1.0.90.

**Comment by p0bo** [comment]
Thank you very much for fast response
