### ISSUE TITLE
[BUG]season anime filter background transparent 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#4]
![Screenshot_2024-07-01-00-55-09-37_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/6ad75f89-dcff-4fda-8b11-4c63c5a90172)
Seasonal anime filer background has no blur making it hard to navigate

**Comment by KanashiiDev** [comment]
Fixed in version 1.0.90.
