### ISSUE TITLE
Some small bug reports 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#5]
##  RSS link overlap with search in article page 
- >![IMG_20240701_222015](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/5ed1eb2f-05c0-4b65-832d-1e6191815fe1)
## FAL page Side blur even though background blur is disabled
- >![IMG_20240701_222215](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/c101aa8b-f2b9-4103-95ab-a4a64b486a9c)
## Settings page custom background not showing
- >![Screenshot_2024-07-01-22-22-53-03_4d38fce200f96aeac5e860e739312e76](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/40b0a66f-ef48-43a5-80fe-e817ddac6d4a)

**Comment by KanashiiDev** [comment]
These bugs fixed in version 1.0.92.
Thanks for your bug reports.
