### ISSUE TITLE
Transparent background of navigation bar bug 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#6]
https://myanimelist.net/forum/?topicid=2138549

>![bug](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/f7d98212-ea71-49c5-afb9-2c9920282b06)

>Steps to reproduce 
-  go to a forum post 
- scroll down 
- now if u notice at the bottom the navigation bar background is transparent which should not be the case

**Comment by KanashiiDev** [comment]
Fixed in version 1.0.93.
