### ISSUE TITLE
Wide forum and review page 

### ISSUE THREAD

**Issue by Buxuna** [KanashiiDev/personal-stylesheets#7]
# # Can we have wide forum and review pages just like wide anime manga page 
// @match        https://myanimelist.net/forum*
// @match        https://myanimelist.net/reviews.php*

I have a wide screen and I use those pages so much and the pages look cramped in my screen if this is implemented it will help a lot . I would like to have whole myanimelist wide if possible but that will be too much to be  asking from a single dev.

Love ♥️your work have been using for a while, recently found out it had github .

**Comment by KanashiiDev** [comment]
> I would like to have whole myanimelist wide if possible but that will be too much to be asking from a single dev.

Yes it is very complicated and difficult to make the whole myanimelist wide.

The improvements you requested have been added in version 1.0.94.
Thank you for using my userstyle!
