### ISSUE TITLE
Theme started closing itself

### ISSUE THREAD

**Issue by shdwns** [KanashiiDev/personal-stylesheets#8]
The theme doesn't work even when it's activated on Stylus. 
When I restart my browser or refresh the page or navigate to a different part of the site, it stops being applied.
![image](https://github.com/user-attachments/assets/58a28135-9ae5-4d6b-b4a5-48db0ad7a78f)
I can get it to work by simply de-activating and activating but it only works for that one time.

**Comment by KanashiiDev** [comment]
It could be browser related or caused by another browser extension.
If you have other browser extensions enabled, please disable them and try again.

**Comment by shdwns** [comment]
It seems to be caused by uBlock Origin. Weird but still fixed the problem for me. Thanks!
