### ISSUE TITLE
Wide Seasonal Anime page 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#9]
**Is your feature request related to a problem? Please describe.**
I really love the wide page settings (anime,manga and forum) that was introduced few months ago and dont mind having other pages normal width but it still bugs me when i open [seasonal page](https://myanimelist.net/anime/season) cause of its not so wide layout .

**Describe the solution you'd like**
I would really love it the page has a width settings just like the some of  other pages .  

|![Screenshot 2024-11-13 103515](https://github.com/user-attachments/assets/95c5875a-b44c-47a9-ba86-f74ab887902c)|
|---|
|![Screenshot 2024-11-13 103417](https://github.com/user-attachments/assets/a5331d65-f073-4996-8d24-629574173d67)|

**Additional context**
Thank you for your work , as a long term user i recommend every friend of mine who uses myanimelist to use this stylesheet

**Comment by KanashiiDev** [comment]
I had added the seasonal page width feature earlier, but I removed it because it wasn't working properly. However, with version 1.1.04, I fixed it and added the feature back again.
Thank you for using my userstyle and recommending it to your friends!
